/* Registration uses isolated accounts and the real website/API; no live OAuth calls. */
const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path');
const {prepare}=require('./browser_support.cjs');
const base=process.env.NFC_TEST_URL,seed=JSON.parse(process.env.V10_SEED),out=path.resolve('.local_registration_v10/current-tests');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || undefined}),errors=[],checks=[],network=[];
 try{
  const check=name=>{checks.push(name);console.log('PASS: '+name);};
  async function pageFor(){const context=await browser.newContext();await prepare(context,base);const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>network.push({url:r.url(),failure:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)network.push({url:r.url(),status:r.status()});});return {context,page};}
  const passwords=async page=>{await page.getByLabel('Password',{exact:true}).fill('BrowserPass!2026');await page.getByLabel('Confirm password',{exact:true}).fill('BrowserPass!2026');};
  const fill=async(page,name)=>{await page.getByRole('textbox',{name:'Player name (for login and display)',exact:true}).fill(name);await passwords(page);};
  const choose=async(page,name,keyboard=false)=>{const field=page.getByRole('combobox',{name:'Find your player name',exact:true});await field.fill(name);await page.getByRole('option',{name,exact:true}).waitFor();if(keyboard){await field.press('ArrowDown');await field.press('Enter');}else await page.getByRole('option',{name,exact:true}).click();await page.locator('[data-selected-claim-player]').filter({hasText:name}).waitFor();};
  const session=async client=>(await client.context.request.get(base+'/api/session')).json();
  const applicant=await pageFor(),p=applicant.page;
  await p.goto(base+'/');await p.locator('header').getByRole('link',{name:'Register',exact:true}).waitFor();assert.equal(await p.locator('header').getByRole('link',{name:'Log In',exact:true}).count(),1);
  await p.locator('header').getByRole('link',{name:'Register',exact:true}).click();await p.getByRole('heading',{name:'Register',exact:true}).waitFor();assert.equal(new URL(p.url()).pathname,'/register');
  assert.equal(await p.getByRole('tab').count(),2);assert.equal(await p.getByRole('tab',{name:'Existing Player',exact:true}).getAttribute('aria-selected'),'true');assert.equal(await p.locator('input[type="email"],input[name="legacy_id"],input[name="player_id"],input[name="username"]').count(),0);
  const search=p.getByRole('combobox',{name:'Find your player name',exact:true});await search.fill('Missing Legacy');await p.getByText('No available player name found.',{exact:false}).waitFor();assert(await p.getByRole('button',{name:'Submit for approval',exact:true}).isDisabled());
  let rejectLookup=true;const lookup=async route=>{if(new URL(route.request().url()).searchParams.get('q')==='Legacy Browser'&&rejectLookup){rejectLookup=false;await route.fulfill({status:503,json:{message:'temporarily unavailable'}});}else await route.continue();};await p.route('**/api/register/players?*',lookup);
  await search.fill('Legacy Browser');await p.getByRole('alert').filter({hasText:'Player names could not be loaded.'}).waitFor();assert.equal(await search.inputValue(),'Legacy Browser');assert(await p.getByRole('button',{name:'Submit for approval',exact:true}).isDisabled());await p.getByRole('button',{name:'Retry search',exact:true}).click();await p.getByText('Searching player names…',{exact:true}).waitFor();await p.getByRole('option',{name:'Legacy Browser',exact:true}).waitFor();await search.press('ArrowDown');assert(await search.getAttribute('aria-activedescendant'));await search.press('Escape');assert.equal(await search.getAttribute('aria-expanded'),'false');await search.press('ArrowDown');await search.press('Enter');await p.locator('[data-selected-claim-player]').getByText('Login and display name: Legacy Browser',{exact:true}).waitFor();await p.unroute('**/api/register/players?*',lookup);
  assert(!(await p.locator('[data-registration-page]').innerText()).includes('club-'+seed.legacy_id));await passwords(p);await p.getByLabel('Confirm password',{exact:true}).fill('Mismatch!2026');await p.getByRole('button',{name:'Submit for approval',exact:true}).click();await p.getByRole('alert').filter({hasText:'Passwords must match.'}).waitFor();assert.equal((await session(applicant)).user,null);
  await p.getByRole('button',{name:'CN',exact:true}).click();await p.getByRole('alert').filter({hasText:'两次输入的密码必须一致'}).waitFor();assert.equal(await p.getByRole('combobox',{name:'搜索已有玩家姓名',exact:true}).inputValue(),'Legacy Browser');assert.equal(await p.locator('input[name="username"]').count(),0);await p.getByRole('button',{name:'EN',exact:true}).click();
  check('Existing Player is the default: name-only accessible search, no username or ID field, empty/loading/error feedback and keyboard retry/selection preserve input across languages');
  await passwords(p);const claimPosted=p.waitForResponse(r=>r.url().endsWith('/api/register/claim')&&r.request().method()==='POST');await p.getByRole('button',{name:'Submit for approval',exact:true}).click();const claimReply=await claimPosted;assert(claimReply.ok(),await claimReply.text());const claimBody=claimReply.request().postDataJSON();assert.equal(claimBody.player_id,'club-'+seed.legacy_id);assert(!('username' in claimBody));assert(!('legacy_id' in claimBody));await p.getByRole('heading',{name:'Waiting for administrator approval',exact:true}).waitFor();
  assert.equal((await session(applicant)).user,null);assert.equal(await p.locator('input[type="password"]').count(),0);await p.reload();await p.getByRole('heading',{name:'Waiting for administrator approval',exact:true}).waitFor();
  check('claim submits only the selected stable player plus passwords and remains unauthenticated pending approval across reload');
  const admin=await pageFor();assert((await admin.context.request.post(base+'/api/login',{data:{username:'photo1',password:'photo-test-password'}})).ok());admin.page.on('dialog',d=>d.accept());
  await admin.page.goto(base+'/?page=admin');const claim=admin.page.locator('[data-account-claim]').filter({hasText:'Legacy Browser'});await claim.getByRole('button',{name:'Approve',exact:true}).waitFor();
  const reviewed=admin.page.waitForResponse(r=>r.url().endsWith('/account-claims/review'));await claim.getByRole('button',{name:'Approve',exact:true}).click();assert((await reviewed).ok());
  await p.getByRole('button',{name:'Check status',exact:true}).click();await p.waitForURL(base+'/',{waitUntil:'domcontentloaded'});assert.equal((await session(applicant)).user,'Legacy Browser');assert(!(await claim.innerText()).includes('→'));const sameName=await applicant.context.request.post(base+'/api/login',{data:{username:'Legacy Browser',password:'BrowserPass!2026'}});assert(sameName.ok(),await sameName.text());
  await p.goto(base+'/register');await p.waitForURL(base+'/',{waitUntil:'domcontentloaded'});await p.getByRole('button',{name:'Log Out',exact:true}).waitFor();assert.equal(await p.locator('header').getByRole('link',{name:/^(Register|Log In)$/}).count(),0);
  check('administrator approval opens the original player name unchanged, permits same-name login, and redirects already logged-in users away from registration');
  const denied=await pageFor();await denied.page.goto(base+'/register');await choose(denied.page,'Legacy Rejected');await passwords(denied.page);await denied.page.getByRole('button',{name:'Submit for approval',exact:true}).click();await denied.page.getByRole('heading',{name:'Waiting for administrator approval',exact:true}).waitFor();
  await admin.page.reload();const rejectedClaim=admin.page.locator('[data-account-claim]').filter({hasText:'Legacy Rejected'});await rejectedClaim.getByRole('button',{name:'Reject',exact:true}).click();await rejectedClaim.getByText(/Rejected ·/).waitFor();
  await denied.page.getByRole('button',{name:'Check status',exact:true}).click();await denied.page.getByRole('alert').filter({hasText:'Your claim was not approved'}).waitFor();assert.equal((await session(denied)).user,null);
  check('a rejected claim never logs in and gives a clear administrator-contact result');
  const newcomer=await pageFor(),n=newcomer.page,target='/?page=record&table=1&pending_seat=east#registration-return';
  await n.goto(base+'/register?redirect_url='+encodeURIComponent(target));await n.getByRole('combobox',{name:'Find your player name',exact:true}).fill('Legacy Browser');await n.getByText('No available player name found.',{exact:false}).waitFor();assert.equal(await n.getByRole('option',{name:'Legacy Browser',exact:true}).count(),0);assert(await n.getByRole('button',{name:'Submit for approval',exact:true}).isDisabled());
  const claimed=await newcomer.context.request.post(base+'/api/register/claim',{data:{player_id:'club-'+seed.legacy_id,password:'BrowserPass!2026',confirm_password:'BrowserPass!2026'}});assert(!claimed.ok());assert.equal((await claimed.json()).message,'This ID is already registered. Please log in or contact an administrator.');
  await n.getByRole('tab',{name:'New Player',exact:true}).click();await fill(n,' ＰＨＯＴＯ１ ');await n.getByRole('button',{name:'Create account',exact:true}).click();await n.getByRole('alert').filter({hasText:'This registered name is already in use.'}).waitFor();
  check('already registered players are absent from the claim picker, forged claims disclose no owner, and duplicate new player names are rejected');
  await fill(n,'Browser New');const created=n.waitForResponse(r=>new URL(r.url()).pathname==='/api/register'&&r.request().method()==='POST');await n.getByRole('button',{name:'Create account',exact:true}).dblclick();assert((await created).ok());
  await n.waitForURL(url=>url.searchParams.get('page')==='record',{waitUntil:'domcontentloaded'});assert.equal((await session(newcomer)).user,'Browser New');assert.equal(new URL(n.url()).hash,'#registration-return');
  await n.frameLocator('#record-game iframe').locator('[data-seat-card="east"][data-seat-state="current"]').waitFor();assert.equal(await n.locator('[data-registration-page],input[type="password"]').count(),0);
  assert(!(await n.evaluate(()=>JSON.stringify([localStorage,sessionStorage]))).includes('BrowserPass!2026'));
  check('new registration skips optional Discord, automatically logs in, preserves the original table/hash and resumes its requested seat');
  const discord=await pageFor(),d=discord.page;await d.goto(base+'/register?redirect_url='+encodeURIComponent('/?tournament='+seed.tid));await d.getByRole('tab',{name:'New Player',exact:true}).click();await fill(d,'Browser Discord');await d.getByRole('checkbox',{name:'Bind Discord Account (Optional)',exact:true}).check();await d.getByRole('button',{name:'Create account',exact:true}).click();
  await d.waitForURL(url=>url.pathname==='/registration-complete',{waitUntil:'domcontentloaded'});await d.getByRole('button',{name:'Bind Discord Account (Optional)',exact:true}).click();await d.getByRole('alert').filter({hasText:'Discord binding is currently unavailable'}).waitFor();assert.equal((await session(discord)).user,'Browser Discord');
  await d.getByRole('link',{name:'Skip for Now / Continue',exact:true}).click();await d.waitForURL(url=>url.searchParams.get('tournament')===seed.tid,{waitUntil:'domcontentloaded'});
  check('optional Discord failure preserves the new account and Skip returns to the original tournament');
  const guest=await pageFor(),g=guest.page;await g.goto(base+seed.guest_path);await g.getByRole('textbox',{name:'Temporary name',exact:true}).fill('Browser Guest');await g.locator('[data-guest-seat="east"]').click();const guestJoined=g.waitForResponse(r=>new URL(r.url()).pathname==='/api/guest/tournaments/'+seed.tid+'/join'&&r.request().method()==='POST');await g.getByRole('button',{name:'Join table',exact:true}).click();const guestReply=await guestJoined;assert(guestReply.ok(),await guestReply.text());await g.waitForURL(/tournament=/,{waitUntil:'domcontentloaded'});
  const identity=async()=>(await guest.context.request.get(base+'/api/guest/tournaments/'+seed.tid)).json();await g.locator('[data-guest-join]').getByText('Browser Guest · Guest',{exact:true}).first().waitFor().catch(async error=>{const diagnostic={url:g.url(),identity:await identity(),body:await g.locator('body').innerText(),errors,network};fs.writeFileSync(path.join(out,'guest-failure.json'),JSON.stringify(diagnostic,null,2));await g.screenshot({path:path.join(out,'guest-failure.png'),fullPage:true});console.error('GUEST DIAGNOSTIC',JSON.stringify(diagnostic));throw error;});const id=(await identity()).participant.id;await g.reload();assert.equal((await identity()).participant.id,id);assert.equal((await session(guest)).user,null);assert(!(await g.locator('body').innerText()).includes(id));
  check('guest QR entry requires only a temporary name and a seat, retains anonymous identity and hides its internal ID');
  await admin.page.goto(base+'/manual-score?tournament='+seed.tid);await admin.page.getByRole('heading',{name:'Competition manual scoring',exact:true}).waitFor();await admin.page.getByRole('combobox').first().waitFor().catch(async error=>{console.error('MANUAL DIAGNOSTIC',JSON.stringify({url:admin.page.url(),session:await session(admin),body:await admin.page.locator('body').innerText(),errors,network}));throw error;});await admin.page.getByRole('combobox').first().fill('Browser Guest');await admin.page.getByRole('option',{name:'Browser Guest',exact:true}).waitFor();assert(await admin.page.getByRole('button',{name:'Create Guest',exact:true}).isVisible());
  const mobile=await pageFor();await mobile.page.setViewportSize({width:390,height:844});await mobile.page.goto(base+'/register');await mobile.page.getByRole('heading',{name:'Register',exact:true}).waitFor();await mobile.page.getByRole('button',{name:'CN',exact:true}).click();await mobile.page.getByRole('tab',{name:'已有玩家开通账号',exact:true}).waitFor();assert(await mobile.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mobile.page.screenshot({path:path.join(out,'register-mobile.png'),fullPage:true});
  check('competition manual lookup includes scoped Guests, and Chinese registration fits a 390px viewport');
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'registration-browser.json'),JSON.stringify({passed:true,checks,errors},null,2));console.log('Registration V10 passed '+checks.length+' checks.');
 }finally{fs.writeFileSync(path.join(out,'registration-network.json'),JSON.stringify({checks,errors,network},null,2));await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
