
const fs=require("fs"),path=require("path"),assert=require("assert"),{chromium}=require("playwright");
const {prepare,root}=require("./browser_support.cjs"),base=process.env.NFC_TEST_URL;
(async()=>{
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || undefined,headless:true});
 try{
  const admin=await browser.newContext({acceptDownloads:true}),players=await browser.newContext();
  await prepare(admin,base);await prepare(players,base);
  assert((await admin.request.post(base+"/api/login",{data:{username:"photo1",password:"photo-test-password"}})).ok());
  const page=await admin.newPage(),user=await players.newPage(),errors=[],network=[];
  for(const p of [page,user]){p.on("pageerror",e=>errors.push(e.message));p.on("requestfailed",r=>network.push({url:r.url(),failure:r.failure()?.errorText}));p.on("response",async r=>{if(r.url().includes("account-avatar.js")||r.status()>=400)network.push({url:r.url(),status:r.status(),contentType:r.headers()["content-type"],length:r.headers()["content-length"]});});p.on("dialog",d=>d.accept());p.setDefaultTimeout(10000);}
  const post=async(url,data)=>{const r=await admin.request.post(base+url,{data});assert(r.ok(),await r.text());return r.json();};
  await page.goto(base+"/");
  await page.getByRole("button",{name:"Admin",exact:true}).click();
  await page.getByLabel("Table Number (positive integer)",{exact:true}).first().fill("33");
  await page.getByRole("button",{name:"Create Table",exact:true}).click();
  const tableCard=page.locator("details").filter({has:page.locator("summary").filter({hasText:/^Table 33 /})}).first();
  await tableCard.locator("summary").first().click();
  const eastToken=tableCard.locator('[data-table-token="east"]');
  await eastToken.getByRole("button",{name:"Create QR Code",exact:true}).click();
  const qrImg=eastToken.getByRole("img");await qrImg.waitFor();
  const qrInput=eastToken.getByRole("textbox",{name:"East · Entry Link",exact:true});
  const entry=await qrInput.inputValue();
  const downloadEvent=page.waitForEvent("download");
  await eastToken.getByRole("button",{name:"Download QR Code",exact:true}).click();
  const download=await downloadEvent;assert(download.suggestedFilename().includes("33"));
  assert(fs.readFileSync(await download.path()).equals(await(await page.request.get(base+await qrImg.getAttribute("src"))).body()));
  await tableCard.getByRole("button",{name:"Create NFC Link",exact:true}).click();
  const nfcInput=tableCard.getByRole("textbox",{name:"NFC · Entry Link",exact:true});await nfcInput.waitFor();
  const nfc=await nfcInput.inputValue();
  await user.goto(entry);
  await user.waitForURL(url=>url.pathname==="/login");
  await user.locator('input[name="username"]').first().fill("photo2");
  await user.locator('input[name="password"]').fill("photo-test-password");
  await user.getByRole("button",{name:"Log in",exact:true}).click();
  await user.waitForURL(url=>url.searchParams.get("page")==="record");
  await user.frameLocator("#record-game iframe").locator('[data-seat-card="east"][data-seat-state="current"]').waitFor();
  await user.goto(entry);await user.waitForURL(url=>url.searchParams.get("page")==="record");
  const list=await(await admin.request.get(base+"/api/admin/club-tables")).json();
  const table=list.tables.find(t=>t.number===33);assert.equal(table.player_count,1);
  assert.equal(table.members[0].join_method,"qr_east");
  assert((await players.request.post(base+"/api/club-tables/"+table.id+"/leave",{data:{}})).ok());
  await user.goto(nfc);await user.waitForURL(url=>url.searchParams.get("page")==="record");
  let current=await(await admin.request.get(base+"/api/admin/club-tables")).json();
  assert.equal(current.tables.find(t=>t.id===table.id).members[0].join_method,"nfc");
  assert.equal(await user.locator("#language").count(),0);
  const frame=user.frameLocator("#record-game iframe");assert.equal(await frame.locator("#language").count(),0);assert.equal(await frame.locator("#qr-download").count(),0);
  assert.equal(await user.locator("[data-reservation-form]").count(),0);
  await user.getByRole("link",{name:"View Table Reservations",exact:true}).click();
  await user.waitForURL(url=>url.pathname==="/reservations");
  await user.getByLabel("Month",{exact:true}).fill("9");
  await user.getByLabel("Day",{exact:true}).fill("20");
  await user.getByLabel("Time",{exact:true}).fill("18:00");
  await user.getByLabel("End Month",{exact:true}).fill("9");
  await user.getByLabel("End Day",{exact:true}).fill("20");
  await user.getByLabel("End Time",{exact:true}).fill("20:00");
  await user.getByLabel("Note (optional)",{exact:true}).fill("Browser reservation");
  await user.getByRole("button",{name:"CN",exact:true}).click();
  assert.equal(await user.getByLabel("时间",{exact:true}).inputValue(),"18:00");
  assert.equal(await user.getByLabel("结束时间",{exact:true}).inputValue(),"20:00");
  await user.getByRole("button",{name:"EN",exact:true}).click();
  const reservationResponse=user.waitForResponse(r=>r.url().endsWith("/reservations")&&r.request().method()==="POST");
  await user.getByRole("button",{name:"Reserve This Table",exact:true}).click();
  const reservedResponse=await reservationResponse;assert(reservedResponse.ok(),await reservedResponse.text());
  const reserved=await reservedResponse.json();assert.equal(Date.parse(reserved.end_at)-Date.parse(reserved.start_at),7200000);
  assert(reserved.session_id);assert.equal(reserved.session.table_id,table.id);
  await user.getByText("Browser reservation",{exact:false}).waitFor();
  await user.goto(base+"/?page=record&table="+encodeURIComponent(table.score_table_id));
  await page.goto(base+"/?page=admin");await tableCard.locator("summary").first().waitFor().catch(async error=>{console.error("ADMIN DIAGNOSTIC",JSON.stringify({url:page.url(),session:await(await admin.request.get(base+"/api/session")).json(),tables:await(await admin.request.get(base+"/api/admin/club-tables")).json(),body:await page.locator("body").innerText(),avatar:await page.evaluate(()=>({type:typeof window.AccountAvatars,scripts:[...document.scripts].map(s=>s.src)})),errors,network}));throw error;});await tableCard.locator("summary").first().click();
  for(const [name,seat] of [["photo3","south"],["photo4","west"],["photo5","north"]]){
   await tableCard.getByRole("button",{name:"Join Table",exact:true}).click();
   await page.getByRole("tab",{name:"Seat by Registered Name",exact:true}).click();
   await page.getByRole("dialog").getByRole("combobox",{name:"Registered Name",exact:true}).fill(name);
   await page.getByRole("option",{name,exact:true}).click();
   await page.getByRole("dialog").getByRole("combobox",{name:"Choose a Seat",exact:true}).selectOption(seat);
   const addResponse=page.waitForResponse(r=>r.url().endsWith("/players")&&r.request().method()==="POST");
   await page.getByRole("dialog").getByRole("button",{name:"Add Selected Player",exact:true}).click();
   const added=await addResponse;assert(added.ok(),await added.text());
   await page.getByRole("dialog").waitFor({state:"detached"});
  }
  await user.reload();await frame.locator("#players").getByText("photo5",{exact:true}).waitFor();
  assert.equal(await user.getByRole("button",{name:"Leave Table",exact:true}).count(),0);
  assert(await frame.locator("[data-seat-card]").evaluateAll(nodes=>nodes.length===4&&nodes.every(n=>n.disabled||n.dataset.seatState==="current")));
  assert.equal((await players.request.post(base+"/api/club-tables/"+table.id+"/leave",{data:{}})).status(),409);
  const reset=await post("/api/admin/club-tables/"+table.id+"/reset",{request_id:"reset-browser",reason:"Browser test cleanup"});
  assert(reset.reset);
  // Revoke NFC through the actual management control.
  await tableCard.getByRole("button",{name:"Revoke Link",exact:true}).last().click();
  await user.goto(nfc);
  await user.getByText("This entry is no longer valid. Reopen the table entry.",{exact:false}).waitFor();
  assert.equal(await user.getByRole("button",{name:"Create QR Code",exact:true}).count(),0);
  // Unlimited creation, retired controls absent, and soft deletion from management.
  await page.getByRole("button",{name:"Tournament Mode",exact:true}).click();
  assert.equal(await page.getByLabel("Raw Point Step",{exact:true}).count(),0);
  assert.equal(await page.getByLabel("Point Divisor",{exact:true}).count(),0);
  assert.equal(await page.getByLabel("Minimum Score Unit",{exact:true}).count(),0);
  await page.getByRole("textbox",{name:"Tournament Name",exact:true}).fill("Delete Browser Cup");
  await page.getByLabel("Match Time",{exact:true}).selectOption("limited");
  assert(await page.getByRole("button",{name:"Create Tournament",exact:true}).isDisabled());
  await page.getByLabel("Match Time",{exact:true}).selectOption("unlimited");
  await page.getByRole("button",{name:"Create Tournament",exact:true}).click();
  await page.getByRole("heading",{name:"Delete Browser Cup · Draft",exact:true}).waitFor();
  const tid=new URL(page.url()).searchParams.get("tournament");
  assert.equal((await(await page.request.get(base+"/api/tournaments/"+tid)).json()).settings.time_limit_seconds,null);
  await page.locator("summary").filter({hasText:"Delete Tournament"}).click();
  await page.getByLabel("Type the tournament name to confirm",{exact:true}).fill("Delete Browser Cup");
  await page.getByLabel("Reason for deletion",{exact:true}).fill("Test duplicate");
  await page.getByRole("button",{name:"Delete Tournament",exact:true}).click();
  await page.getByRole("heading",{name:"Delete Browser Cup · Draft",exact:true}).waitFor({state:"detached"});
  assert.equal((await page.request.get(base+"/api/tournaments/"+tid)).status(),410);
  assert.deepEqual(errors,[]);
  console.log("Table browser workflow passed: QR PNG, NFC, login return, repeated scan, leave, reservation, registered names, global language, unlimited timer and deletion.");
 } finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
