const assert=require("assert"),fs=require("fs"),path=require("path"),{chromium}=require("playwright");
const base=process.env.CHALLENGE_TEST_URL||"http://127.0.0.1:5083";
assert.equal(new URL(base).hostname,"127.0.0.1","Writable UI tests require the isolated local preview");
const out=path.resolve(".local_challenge_v11/browser");fs.mkdirSync(out,{recursive:true});
const report={checks:[],errors:[],screenshots:[]};
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || undefined,headless:true});try{
 const context=await browser.newContext({viewport:{width:1440,height:1050}}),page=await context.newPage();page.setDefaultTimeout(20000);page.on("pageerror",e=>report.errors.push(e.message));
 await page.goto(base);await page.locator("[data-current-challenge] h2").waitFor();
 assert((await page.locator("[data-current-challenge]").innerText()).includes("Upcoming"));
 const initial=await (await context.request.get(base+"/api/competitions/featured")).json(),slug=initial.competition.slug;
 assert.deepEqual(initial.leaderboard.map(r=>r.total),[7,5,3,2]);
 assert.equal(await page.locator("[data-challenge-board] tbody > tr").count(),4);
 assert.equal(await page.locator('[data-current-challenge] button').filter({hasText:/register|sign up|join/i}).count(),0);
 await page.getByRole("link",{name:"View Full Leaderboard",exact:true}).click();await page.getByLabel("Search player names").fill("Alice");
 await page.waitForFunction(()=>document.querySelectorAll("[data-challenge-board] tbody > tr").length===1);
 await page.getByRole("button",{name:"Alice",exact:true}).click();await page.getByText("7 + 2 =").count();
 await page.waitForFunction(()=>document.querySelector('[data-challenge-board]').textContent.includes('5 + 2 = 7'));
 report.checks.push("Home, complete leaderboard, search, 7/5/3/2 scores, no enrollment, per-game breakdown");
 const denied=await context.request.post(base+"/api/competitions/"+slug+"/content",{data:{title:"Unauthorized"},headers:{Origin:base}});assert.equal(denied.status(),401);
 const login=await context.request.post(base+"/api/login",{data:{username:"PreviewAdmin",password:"LocalTest!2026"},headers:{Origin:base}});assert(login.ok(),await login.text());
 await page.goto(base+"/?page=admin");await page.getByRole("heading",{name:"Date-window Competition Management"}).waitFor();
 const managed=await (await context.request.get(base+"/api/competitions/"+slug+"/admin")).json();
 const editor=page.locator('[data-i18n-owned]').filter({has:page.getByRole("heading",{name:"Date-window Competition Management"})});
 await editor.getByLabel("Introduction (headings, lists and paragraphs)",{exact:true}).fill("# Preview Heading\n\n- Safe list\n- Everyone participates\n\n<script>window.challengeXss=1</script>");
 await editor.getByLabel("Image Alternative Text",{exact:true}).fill("UC San Diego Mahjong club emblem");
 await editor.locator('input[type="file"]').setInputFiles(path.resolve("web/assets/UCSD_mermaid_whitebg.jpg"));
 await editor.getByLabel("Cover Image",{exact:true}).locator("option").filter({hasText:"UC San Diego Mahjong club emblem"}).first().waitFor({state:"attached"});
 await editor.getByLabel("Cover Image",{exact:true}).selectOption({label:"UC San Diego Mahjong club emblem"});
 await editor.getByRole("button",{name:"Save Draft",exact:true}).click();await editor.getByRole("status").filter({hasText:"Saved"}).waitFor();
 let pub=await (await context.request.get(base+"/api/competitions/"+slug)).json();assert.equal(pub.competition.introduction,initial.competition.introduction);
 await editor.getByRole("button",{name:"Publish Content",exact:true}).click();await page.waitForTimeout(500);
 pub=await (await context.request.get(base+"/api/competitions/"+slug)).json();assert(pub.competition.introduction.includes("Preview Heading"));assert(!pub.competition.introduction.includes("<script"));assert(pub.competition.cover);
 assert.deepEqual(pub.leaderboard.map(r=>r.total),[7,5,3,2]);assert.equal(await page.evaluate(()=>window.challengeXss),undefined);
 report.checks.push("Administrator draft/publish, raster upload, cover selection, XSS safety, unchanged scores");
 // Restore useful event prose after validating draft vs published behavior; keep the local preview cover.
 const latest=await (await context.request.get(base+"/api/competitions/"+slug+"/admin")).json();
 const restore=await context.request.post(base+"/api/competitions/"+slug+"/content",{headers:{Origin:base},data:{...latest.competition.draft,title:initial.competition.title,introduction:initial.competition.introduction,publish:true,published:true,featured:true,leaderboard_public:true,version:latest.competition.version}});assert(restore.ok());
 await page.goto(base);await page.locator('[data-current-challenge] h2').waitFor();
 let file=path.join(out,"challenge-home-desktop.png");await page.screenshot({path:file,fullPage:true});report.screenshots.push(file);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>localStorage.setItem("mahjong_lang","CN"));await page.goto(base+"/challenges/"+slug);await page.locator('[data-current-challenge] h2').waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert((await page.locator('[data-current-challenge]').innerText()).includes("即将开始"));
 file=path.join(out,"challenge-leaderboard-mobile-cn.png");await page.screenshot({path:file,fullPage:true});report.screenshots.push(file);
 report.checks.push("Chinese, 390px mobile no horizontal overflow, original authored prose preserved");
 assert.deepEqual(report.errors,[]);report.passed=true;
}finally{fs.writeFileSync(path.join(out,"report.json"),JSON.stringify(report,null,2));await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
