/* Real tournament settings, scoped Guest enrollment and independent placement scoring. */
const assert=require('assert'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{prepare}=require('./browser_support.cjs');
const base=process.env.NFC_TEST_URL,out=path.resolve('.local_registration_v10/current-tests'),fields=['first_placement_game_score','second_placement_game_score','third_placement_game_score','fourth_placement_game_score','game_participation_score'];
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || undefined,headless:true}),checks=[],errors=[];let page;try{
 fs.mkdirSync(out,{recursive:true});const check=name=>{checks.push(name);console.log('PASS: '+name);};
 async function client(){const context=await browser.newContext();await prepare(context,base);const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));return {context,page};}
 const admin=await client();page=admin.page;assert((await admin.context.request.post(base+'/api/login',{data:{username:'photo1',password:'photo-test-password'}})).ok());page.on('dialog',dialog=>dialog.type()==='prompt'?dialog.accept('Browser verified rule update'):dialog.accept());
 const request=async(url,data,context=admin.context)=>{const response=await context.request.post(base+url,{data});assert(response.ok(),await response.text());return response.json();};
 await page.goto(base+'/?page=tournament');await page.getByRole('textbox',{name:'Tournament Name',exact:true}).fill('V10 UI Cup');const create=page.getByRole('button',{name:'Create Tournament',exact:true}),initial=page.locator('[data-placement-settings]').first();
 assert.equal(await initial.getByRole('checkbox').isChecked(),false);await initial.getByRole('combobox').selectOption('placement_and_game_count');
 assert.equal(await initial.locator('input[type="number"]').count(),5);assert.deepEqual(await initial.locator('input[type="number"]').evaluateAll(nodes=>nodes.map(node=>node.value)),['','','','','']);assert(await create.isDisabled());
 for(let i=0;i<4;i++)await initial.locator('input[name="'+fields[i]+'"]').fill(String([5,3,1,0][i]));assert(await create.isDisabled());await initial.locator('input[name="game_participation_score"]').fill('-0.25');assert(!await create.isDisabled());
 await initial.getByRole('combobox').selectOption('return');assert.equal(await initial.locator('input[type="number"]').count(),0);await initial.getByRole('combobox').selectOption('placement_and_game_count');assert.equal(await initial.locator('input[name="game_participation_score"]').inputValue(),'-0.25');await initial.locator('input[name="game_participation_score"]').fill('2');await initial.getByRole('checkbox').check();
 const created=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/tournaments'&&r.request().method()==='POST');await create.click();const createdResponse=await created;assert(createdResponse.ok(),await createdResponse.text());const cup=await createdResponse.json(),tid=cup.id;
 await page.getByRole('heading',{name:'V10 UI Cup · Draft',exact:true}).waitFor();assert.equal(cup.settings.scoring_mode,'placement_and_game_count');assert.equal(cup.settings.allow_guest_auto_enrollment,true);
 check('new mode requires all five administrator-entered scores, accepts negative/zero values and preserves them when switching modes; Guest defaults off');
 const get=async()=>(await admin.context.request.get(base+'/api/tournaments/'+tid+'/admin')).json();
 const action=async(action,data={})=>{const state=await get();return request('/api/tournaments/'+tid+'/actions',{action,data:{...data,version:state.version,request_id:crypto.randomUUID()}});};
 const settings=page.locator('details').filter({has:page.locator('summary').filter({hasText:/^Tournament Settings$/})}).first();await settings.locator('[data-placement-settings] input[name="fourth_placement_game_score"]').fill('-1');
 const settingsSaved=page.waitForResponse(r=>r.request().method()==='POST'&&r.request().postDataJSON()?.action==='settings');await settings.getByRole('button',{name:'Save',exact:true}).click();assert((await settingsSaved).ok());assert.equal((await get()).settings.fourth_placement_game_score,-1);
 await action('settings',{settings:{fourth_placement_game_score:0}});await page.reload();
 const roster=page.getByRole('combobox',{name:'Player Name',exact:true}).first();await roster.fill('photo1');await page.getByRole('option',{name:'photo1',exact:true}).click();await page.getByRole('button',{name:'Add Player',exact:true}).click();await page.locator('[data-tournament-roster] li').filter({hasText:'photo1'}).waitFor();
 assert.equal(await page.locator('[data-tournament-roster] [data-account-avatar]').count(),1);assert(!(await page.locator('[data-tournament-roster]').innerText()).includes('Guest'));
 assert.equal(await page.locator('[data-placement-rankings] th').count(),11);assert(!(await page.locator('[data-placement-rankings]').innerText()).match(/Return|Uma|Converted|Raw/i));
 check('editing saves exact placement scores; a registered roster player has an avatar and is never mislabeled Guest; rankings show all nine metrics');
 const table=await request('/api/admin/club-tables',{number:51,tournament_id:tid,request_id:crypto.randomUUID()});
 const qr=await request('/api/admin/club-tables/'+table.id+'/tokens',{channel:'qr',purpose:'seat_join',seat:'west',request_id:crypto.randomUUID()});
 const nfc=await request('/api/admin/club-tables/'+table.id+'/tokens',{channel:'nfc',request_id:crypto.randomUUID()});
 const guest=await client(),g=guest.page;await g.goto(base+qr.path+'?seat=east');await g.getByRole('textbox',{name:'Temporary name',exact:true}).fill('QR Guest');
 assert.equal(await g.locator('[data-guest-seat]').count(),4);assert(await g.locator('[data-guest-seat="east"]').isDisabled());assert.equal(await g.locator('[data-guest-seat="west"]').getAttribute('aria-pressed'),'true');await g.getByRole('button',{name:'Join table',exact:true}).click();await g.waitForURL(/tournament=/,{waitUntil:'domcontentloaded'});
 const guestInfo=async context=>(await context.request.get(base+'/api/guest/tournaments/'+tid)).json();let identity=await guestInfo(guest.context);const guestId=identity.participant.id;assert.equal(identity.current_membership.seat,'west');
 await g.goto(base+qr.path);assert.equal(await g.getByRole('textbox',{name:'Temporary name',exact:true}).count(),0);await g.getByRole('button',{name:'Join table',exact:true}).click();await g.waitForURL(/tournament=/,{waitUntil:'domcontentloaded'});assert.equal((await guestInfo(guest.context)).participant.id,guestId);assert.equal((await get()).players.filter(p=>p.name==='QR Guest').length,1);
 await g.locator('[data-guest-join]').getByText('QR Guest · Guest',{exact:true}).first().waitFor();assert(!(await g.locator('body').innerText()).includes(guestId));assert.equal((await(await guest.context.request.get(base+'/api/session')).json()).user,null);
 check('seat QR binds the server wind despite query tampering and repeated scans retain exactly one anonymous Guest without displaying IDs');
 const contact=await client(),c=contact.page;await c.goto(base+nfc.path);await c.getByRole('textbox',{name:'Temporary name',exact:true}).fill('NFC Guest');await c.locator('[data-guest-seat="south"]').click();await c.getByRole('button',{name:'Join table',exact:true}).click();await c.waitForURL(/tournament=/,{waitUntil:'domcontentloaded'});assert.equal((await guestInfo(contact.context)).current_membership.seat,'south');
 const direct=await client(),d=direct.page;await d.goto(base+'/?tournament='+tid+'&table=51');await d.locator('[data-guest-seat="west"]').waitFor();assert(await d.locator('[data-guest-seat="west"]').isDisabled());assert(await d.locator('[data-guest-seat="south"]').isDisabled());await d.locator('[data-guest-seat="east"]').click();await d.getByRole('textbox',{name:'Temporary name',exact:true}).fill(' PHOTO2 ');await d.getByRole('button',{name:'Join table',exact:true}).click();await d.getByRole('status').filter({hasText:'Choose a name different from a registered player.'}).waitFor();
 await d.getByRole('textbox',{name:'Temporary name',exact:true}).fill('Page Guest');await d.getByRole('button',{name:'Join table',exact:true}).click();await d.getByRole('status').filter({hasText:'You joined the table.'}).waitFor();assert.equal((await guestInfo(direct.context)).current_membership.seat,'east');
 check('NFC and explicit competition-page empty seats enroll Guests; occupied winds disable selection and registered-name impersonation is rejected');
 await d.goto(base+'/?page=record&table=web');await d.frameLocator('#record-game iframe').locator('[data-seat-card]').first().waitFor();assert.equal(await d.locator('[data-guest-join]').count(),0);
 const beforeOrdinary=(await get()).players.length;await d.reload();assert.equal((await get()).players.length,beforeOrdinary);
 const restricted=await request('/api/tournaments',{name:'Registered Only Cup',settings:{allow_guest_auto_enrollment:false},request_id:crypto.randomUUID()});await d.goto(base+'/?tournament='+restricted.id);await d.getByRole('heading',{name:'Registered Only Cup · Draft',exact:true}).waitFor();assert.equal(await d.locator('[data-guest-join]').count(),0);
 await page.goto(base+'/manual-score?tournament='+restricted.id);await page.getByRole('heading',{name:'Competition manual scoring',exact:true}).waitFor();await page.getByRole('combobox').first().waitFor();assert.equal(await page.getByRole('button',{name:'Create Guest',exact:true}).count(),0);assert.equal(await page.locator('[data-placement-rankings]').count(),0);
 const restrictedResult=await guest.context.request.post(base+'/api/guest/tournaments/'+restricted.id+'/join',{data:{name:'Forged Guest',table_id:table.id,seat:'north'}});assert([403,409].includes(restrictedResult.status()));
 check('ordinary scoring never enrolls tournament Guests and registered-only competitions expose no Guest creation or new-mode ranking');
 await page.goto(base+'/manual-score?tournament='+tid);await page.getByRole('textbox',{name:'New Guest name',exact:true}).fill('Manual Guest');await page.getByRole('button',{name:'Create Guest',exact:true}).click();await page.getByRole('textbox',{name:'New Guest name',exact:true}).filter({hasText:''}).waitFor();
 const names=['photo1','QR Guest','NFC Guest','Manual Guest'];
 for(let i=0;i<4;i++){await page.getByRole('combobox').nth(i).fill(names[i]);const option=page.getByRole('option',{name:names[i],exact:true});await option.waitFor();assert.equal(await option.locator('[data-account-avatar]').count(),1);if(i)assert((await option.innerText()).includes('Guest'));await option.click();}
 const totals=[];
 for(const scores of [[40000,30000,20000,10000],[30000,40000,10000,20000]]){
  for(let i=0;i<4;i++)await page.getByRole('spinbutton').nth(i).fill(String(scores[i]));await page.getByRole('button',{name:'Preview calculation',exact:true}).click();await page.getByRole('heading',{name:'Game calculation',exact:true}).waitFor();const calc=page.getByRole('heading',{name:'Game calculation',exact:true}).locator('..');assert(!(await calc.innerText()).match(/Return|Uma|Converted|÷/i));
  const saved=page.waitForResponse(r=>r.request().method()==='POST'&&r.request().postDataJSON()?.action==='manual_game');await page.getByRole('button',{name:'Confirm and save game',exact:true}).click();assert((await saved).ok());await page.getByText('Confirmed game saved. Standings are updated.',{exact:true}).waitFor();
 }
 const final=await get(),ranks=final.standings.map(row=>row.rank);assert.equal(final.rounds.length,2);const rows=final.standings.filter(row=>names.includes(row.name));assert.deepEqual(rows.map(row=>row.score),[12,12,5,5]);assert.deepEqual(rows.map(row=>row.rank),[1,1,3,3]);assert(rows.every(row=>row.completed_rounds===2));
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('[data-placement-rankings] tbody tr')).some(row=>row.textContent.includes('12')));assert.equal(await page.locator('[data-placement-rankings] th').count(),11);assert.equal(await page.locator('[data-placement-rankings] [data-account-avatar]').count(),final.standings.length);assert((await page.locator('[data-placement-rankings]').innerText()).includes('QR Guest · Guest'));
 for(const row of final.players)assert(!(await page.locator('body').innerText()).includes(row.id));
 check('competition manual scoring creates and searches scoped Guests with avatars, saves two confirmed games and displays exact independent subtotals and tied ranks');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'CN',exact:true}).click();await page.getByRole('heading',{name:'比赛手动登分',exact:true}).waitFor();assert.equal(await page.locator('[data-placement-rankings]').getByText('管理员调整分',{exact:true}).count(),1);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'tournament-mobile.png'),fullPage:true});
 check('Chinese ranking labels include adjustments and keep the wide metrics table inside the mobile viewport');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'tournament-browser.json'),JSON.stringify({passed:true,checks,errors},null,2));console.log('Tournament V10 passed '+checks.length+' checks.');
}catch(error){if(page)console.error('Tournament diagnostic',page.url(),(await page.locator('body').innerText()).slice(0,4500));throw error;}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
