const fs=require("fs"),path=require("path"),assert=require("assert");
const {chromium}=require("playwright"),babel=require("@babel/core");
const root=path.resolve(__dirname,".."),base=process.env.NFC_TEST_URL;
const compile=p=>babel.transformFileSync(path.join(root,p),{plugins:[[require("@babel/plugin-transform-react-jsx"),{runtime:"classic"}]]}).code;
(async()=>{
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || undefined,headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1280,height:900},acceptDownloads:true});
  await require("./browser_support.cjs").prepare(page.context(),base);
  const errors=[];page.on("pageerror",e=>errors.push(e.message));page.on("dialog",d=>d.type()==="prompt"?d.accept("Browser audit reason"):d.accept());
  await page.route("https://cdn.tailwindcss.com/**",r=>r.fulfill({body:"window.tailwind={};",contentType:"application/javascript"}));
  await page.route("https://unpkg.com/react@18/**",r=>r.fulfill({path:path.join(path.dirname(require.resolve("react/package.json")),"umd/react.development.js"),contentType:"application/javascript"}));
  await page.route("https://unpkg.com/react-dom@18/**",r=>r.fulfill({path:path.join(path.dirname(require.resolve("react-dom/package.json")),"umd/react-dom.development.js"),contentType:"application/javascript"}));
  await page.route("**/table-controls.jsx?*",r=>r.fulfill({body:compile("web/table-controls.jsx"),contentType:"application/javascript"}));
  await page.route("**/app.jsx?*",r=>r.fulfill({body:compile("web/app.jsx"),contentType:"application/javascript"}));
  await page.route("**/tournament-v2.jsx?*",r=>r.fulfill({body:compile("web/tournament-v2.jsx"),contentType:"application/javascript"}));
  await page.route("**/tournament.jsx?*",r=>r.fulfill({body:compile("web/tournament.jsx"),contentType:"application/javascript"}));
  await page.route(url=>url.origin===base&&["/","/login"].includes(url.pathname),r=>r.fulfill({body:fs.readFileSync(path.join(root,"web/index.html"),"utf8").replace(/<script src="https:\/\/unpkg.com\/@babel\/standalone\/babel.min.js"><\/script>/,"").replaceAll('type="text/babel"','type="text/javascript"'),contentType:"text/html"}));
  // Verify the real login entry, failed-login state and home redirect.
  await page.goto(base+"/");
  await page.locator("header").getByRole("link",{name:"Log In",exact:true}).click();
  await page.locator('input[name="password"]').waitFor();
  await page.locator('input[name="username"]').first().fill("photo1");
  await page.locator('input[name="password"]').fill("wrong-test-password");
  await Promise.all([page.waitForResponse(r=>r.url().endsWith("/api/login")),page.getByRole("button",{name:"Log in",exact:true}).click()]);
  assert.equal(new URL(page.url()).pathname,"/login");
  await page.locator('input[name="password"]').fill("photo-test-password");
  await page.getByRole("button",{name:"Log in",exact:true}).click();
  await page.waitForURL(base+"/");
  await page.locator("header").getByRole("link",{name:"Log In",exact:true}).waitFor({state:"hidden"});
  assert.equal(await page.locator("header").getByRole("link",{name:"Log In",exact:true}).count(),0);

  await page.getByRole("button",{name:"Admin",exact:true}).click();
  const field=page.getByLabel("NARTS API Key",{exact:true});
  await field.waitFor();
  assert.equal(await field.getAttribute("type"),"password");
  await page.getByRole("button",{name:"Use NARTS API URL",exact:true}).click();
  const secret="opaque_Browser.Key-AbCd123456";
  await field.fill(secret);
  await page.getByRole("button",{name:"CN",exact:true}).click();
  assert.equal(await page.getByLabel("NARTS API 密钥",{exact:true}).inputValue(),secret);
  await page.getByRole("button",{name:"EN",exact:true}).click();
  assert.equal(await field.inputValue(),secret);
  assert(!(await page.evaluate(()=>JSON.stringify({...localStorage}))).includes(secret));
  await page.getByRole("button",{name:"Test Connection",exact:true}).click();
  await page.getByText("The entered key has not been saved.",{exact:false}).waitFor();
  await field.fill("contains spaces");
  await page.getByRole("button",{name:"Save and Enable Sync",exact:true}).click();
  await page.getByText("The input contains spaces, line breaks or non-ASCII characters",{exact:false}).waitFor();
  await field.fill(secret);
  const connectionTest=page.waitForResponse(r=>r.url().endsWith("/api/external-test"));
  const post=page.waitForResponse(r=>r.url().endsWith("/api/external-config")&&r.request().method()==="POST");
  await page.getByRole("button",{name:"Save and Enable Sync",exact:true}).click();
  assert.equal((await post).status(),200);
  assert.equal((await connectionTest).status(),200);
  await page.getByText("Configuration saved and verified on the website server.",{exact:false}).waitFor();
  await page.getByRole("button",{name:"Save and Enable Sync",exact:true}).waitFor({state:"visible"});
  await page.waitForFunction(()=>document.querySelector('input[aria-label="NARTS API Key"]')?.value==="");
  await page.getByText("Server Key Configured",{exact:false}).waitFor();
  await page.getByText("Automatic Sync Enabled for New Scores",{exact:false}).waitFor();
  const first=await (await page.request.get(base+"/api/external-config")).json();
  assert(first.key_configured&&first.enabled&&first.saved_at);
  assert(!JSON.stringify(first).includes(secret));
  assert.equal(first.last_test.code,"reachable_unverified");
  await page.getByRole("button",{name:"Save Configuration",exact:true}).click();
  await page.getByText("Configuration saved and verified on the website server.",{exact:false}).waitFor();
  await page.reload();
  await page.getByRole("button",{name:"Admin",exact:true}).click();
  await page.getByText("Server Key Configured",{exact:false}).waitFor();
  assert.equal(await field.inputValue(),"");
  const current=await (await page.request.get(base+"/api/external-config")).json();
  assert(current.enabled&&current.key_configured);
  assert(!(await page.evaluate(()=>JSON.stringify({...localStorage}))).includes(secret));
  assert.equal(errors.length,0,JSON.stringify(errors));
  console.log("NARTS browser: masked input, CN/EN preservation, invalid-key feedback, save/enable/HEAD, server read-back, empty-field retention, reload persistence passed");
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
