const assert=require("assert"),{chromium}=require("playwright"),{prepare}=require("./browser_support.cjs");
const base=process.env.NFC_TEST_URL;
(async()=>{
 const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || undefined,headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1360,height:1000}});await prepare(context,base);
  assert((await context.request.post(base+"/api/login",{data:{username:"photo1",password:"photo-test-password"}})).ok());
  let liveGames=[];
  await context.route("**/api/dashboard*",route=>route.fulfill({json:{stats:{member_count:8},rankings:[],recent_yakuman:[],live_games:liveGames}}));
  await context.route("**/api/admin/matches?*",route=>route.fulfill({json:{ok:true,rows:[{id:123,game_id:123,date:"2026-09-18",players:[{name:"Legacy Guest",score:40000},{name:"photo2",score:30000},{name:"photo3",score:20000},{name:"photo4",score:10000}]}],page:1,pages:1}}));
  const page=await context.newPage(),errors=[],writes=[],dashboardQueries=[];page.setDefaultTimeout(15000);
  page.on("pageerror",error=>errors.push(error.message));
  page.on("request",request=>{if(request.method()==="POST")writes.push(request);if(new URL(request.url()).pathname==="/api/dashboard")dashboardQueries.push(new URL(request.url()).searchParams);});
  const choose=async(field,name)=>{await field.fill(name);await page.getByRole("option",{name,exact:true}).click();};
  await page.goto(base+"/");
  const brand="DORA Mahjong Club at UC San Diego";
  await page.getByRole("heading",{name:brand,exact:true}).waitFor();assert.equal(await page.title(),brand);
  assert.equal(await page.locator('meta[property="og:title"]').getAttribute("content"),brand);
  let profile=page.getByRole("combobox",{name:"View player",exact:true});
  await profile.fill("free profile text");await page.getByText("No registered name found.",{exact:true}).waitFor();
  assert(!dashboardQueries.some(query=>query.get("profile_player")==="free profile text"));
  await choose(profile,"photo2");await page.waitForResponse(response=>response.url().includes("profile_player=photo2"));
  await page.getByRole("button",{name:"CN",exact:true}).click();
  assert.equal(await page.getByRole("combobox",{name:"查看玩家",exact:true}).inputValue(),"photo2");
  await page.getByRole("heading",{name:brand,exact:true}).waitFor();assert.equal(await page.title(),brand);
  await page.getByRole("button",{name:"EN",exact:true}).click();
  await page.getByRole("button",{name:"Account",exact:true}).click();
  const own=page.getByRole("textbox",{name:"Your Registered Name",exact:true});await own.waitFor();
  assert.equal(await own.inputValue(),"photo1");assert.equal(await own.evaluate(input=>input.readOnly),true);
  assert.equal(await page.locator("[data-registered-name-admin]").count(),0);
  await page.getByRole("button",{name:"Admin",exact:true}).click();
  const admin=page.locator("[data-registered-name-admin]");await admin.waitFor();
  await page.getByText("Registered name uniqueness is enforced.",{exact:true}).waitFor();
  const roleForm=page.locator("form").filter({has:page.getByRole("button",{name:"Update role",exact:true})});
  const role=roleForm.getByRole("combobox",{name:"Registered Name",exact:true});
  await role.fill("unselected user");await page.getByRole("button",{name:"Update role",exact:true}).click();
  assert.equal(await role.evaluate(input=>input.checkValidity()),false);assert.equal(writes.filter(request=>request.url().endsWith("/api/admin/role")).length,0);
  await choose(role,"photo3");assert.equal(await roleForm.locator('input[type="hidden"][name="username"]').inputValue(),"photo3");
  await role.fill("photo3 edited");await role.fill("photo3");assert.equal(await roleForm.locator('input[type="hidden"][name="username"]').inputValue(),"");assert.equal(await role.evaluate(input=>input.checkValidity()),false);
  const resetForm=page.locator("form").filter({has:page.getByRole("button",{name:"Reset password",exact:true})});
  await choose(resetForm.getByRole("combobox",{name:"Registered Name",exact:true}),"photo4");
  assert.equal(await resetForm.locator('input[type="hidden"][name="username"]').inputValue(),"photo4");
  await page.getByRole("button",{name:"Add yakuman",exact:true}).click();
  await choose(page.getByRole("combobox",{name:"Winner",exact:true}),"Legacy Guest");
  assert.equal(await page.locator('input[type="hidden"][name="winner"]').inputValue(),"Legacy Guest");
  const dealIn=page.getByRole("combobox",{name:"Deal-in (optional)",exact:true});
  await dealIn.fill("unselected optional player");assert.equal(await dealIn.evaluate(input=>input.checkValidity()),false);
  await dealIn.fill("");assert.equal(await dealIn.evaluate(input=>input.checkValidity()),true);
  const target=admin.getByRole("combobox",{name:"Select Registered User",exact:true});await choose(target,"photo2");
  await admin.getByRole("textbox",{name:"New Registered Name",exact:true}).fill("Renamed Photo Two");
  await admin.getByRole("textbox",{name:"Reason (optional)",exact:true}).fill("Correcting registered spelling");
  await page.getByRole("button",{name:"CN",exact:true}).click();
  assert.equal(await admin.getByRole("combobox",{name:"选择注册用户",exact:true}).inputValue(),"photo2");
  assert.equal(await admin.getByRole("textbox",{name:"新注册名",exact:true}).inputValue(),"Renamed Photo Two");
  await page.getByRole("button",{name:"EN",exact:true}).click();
  let cancelled=false;page.once("dialog",async dialog=>{assert(dialog.message().includes("photo2")&&dialog.message().includes("Renamed Photo Two"));cancelled=true;await dialog.dismiss();});
  await admin.getByRole("button",{name:"Confirm Name Change",exact:true}).click();assert(cancelled);
  assert.equal(writes.filter(request=>request.url().endsWith("/api/admin/registered-name")).length,0);
  page.once("dialog",dialog=>dialog.accept());const renamed=page.waitForResponse(response=>response.url().endsWith("/api/admin/registered-name")&&response.request().method()==="POST");
  await admin.getByRole("button",{name:"Confirm Name Change",exact:true}).click();const renameResponse=await renamed;assert(renameResponse.ok(),await renameResponse.text());
  await admin.getByText("Registered name updated; existing records remain linked.",{exact:true}).waitFor();
  const posted=writes.filter(request=>request.url().endsWith("/api/admin/registered-name"));assert.equal(posted.length,1);
  assert.deepEqual(posted[0].postDataJSON(),{user_id:"photo-user-2",expected_name:"photo2",new_name:"Renamed Photo Two",reason:"Correcting registered spelling",confirm:true});
  assert(!(await page.locator("body").innerText()).includes("photo-user-"));
  await page.getByRole("button",{name:"Live",exact:true}).click();
  for(const [index,name] of ["photo1","Renamed Photo Two","photo3","photo4"].entries())await choose(page.getByRole("combobox",{name:`Player ${index+1} Registered Name`,exact:true}),name);
  const started=page.waitForResponse(response=>response.url().endsWith("/api/live-games")&&response.request().method()==="POST");
  await page.getByRole("button",{name:"Start from 25000",exact:true}).click();const startResponse=await started;assert(startResponse.ok(),await startResponse.text());
  const game=(await startResponse.json()).game;assert.equal(game.player2,"Renamed Photo Two");liveGames=[game];
  await page.getByRole("button",{name:"Refresh",exact:true}).click();await page.locator('select[name="game_id"] option[value="'+game.id+'"]').waitFor({state:"attached"});
  await page.locator('select[name="game_id"]').selectOption(String(game.id));
  await choose(page.getByRole("combobox",{name:"Winner",exact:true}),"Renamed Photo Two");
  await page.getByRole("button",{name:"Recent Match",exact:true}).click();
  await choose(page.getByRole("combobox",{name:"Find a Registered Name",exact:true}),"Renamed Photo Two");
  const third=page.getByRole("combobox",{name:"Player 3 Registered Name",exact:true});await choose(third,"photo3");
  assert.equal(await third.inputValue(),"photo3");assert.equal(await page.getByRole("combobox",{name:"Player 1 Registered Name",exact:true}).inputValue(),"");
  assert.equal(await page.locator('input[list],select[name="winner"],select[name="deal_in"]').count(),0);
  assert((await context.request.post(base+"/api/login",{data:{username:"photo5",password:"photo-test-password"}})).ok());
  await page.goto(base+"/login");await page.getByRole("textbox",{name:"Your Registered Name",exact:true}).waitFor();
  assert.equal(await page.getByRole("textbox",{name:"Your Registered Name",exact:true}).inputValue(),"photo5");
  await page.getByRole("button",{name:"Admin",exact:true}).click();
  assert.equal(await page.locator("[data-registered-name-admin]").count(),0);
  assert.deepEqual(errors,[]);console.log("Brand, name-only app selectors, historical roster, read-only profile and confirmed administrator rename passed.");
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
