const assert=require('assert'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{prepare,root}=require('./browser_support.cjs');
const base=process.env.NFC_TEST_URL,out=path.join(root,'.local_seat_cards','v9'),checks=[];
(async()=>{const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || undefined,headless:true});try{
 const admin=await browser.newContext(),actor=await browser.newContext({timezoneId:'Asia/Tokyo',viewport:{width:1280,height:1000}});await prepare(actor,base);
 for(const [context,n] of [[admin,1],[actor,2]])assert((await context.request.post(base+'/api/login',{data:{username:'photo'+n,password:'photo-test-password'}})).ok());
 const post=async(context,url,data)=>{const response=await context.request.post(base+url,{data});assert(response.ok(),await response.text());return response.json();};
 const a=await post(admin,'/api/admin/club-tables',{number:76,request_id:'v9-table-a'}),b=await post(admin,'/api/admin/club-tables',{number:77,request_id:'v9-table-b'});
 const first=await post(admin,'/api/club-tables/'+b.id+'/reservations',{scheduled_at:'2027-01-01T07:20:00+00:00',end_at:'2027-01-01T10:00:00+00:00',participant_ids:['photo-user-3'],request_id:'v9-first'});
 const page=await actor.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 const form=page.locator('[data-reservation-form]'),field=name=>form.getByLabel(name,{exact:true}),tableSelect=page.getByLabel('Select Table',{exact:true});
 const waitValue=async(name,value)=>{await page.waitForFunction(({name,value})=>document.querySelector('[data-reservation-form] input[aria-label="'+name+'"]')?.value===value,{name,value});};
 const check=text=>{checks.push(text);console.log('PASS: '+text);};
 const save=async(edit=false)=>{const wait=page.waitForResponse(r=>r.request().method()==='POST'&&(edit?r.url().includes('/api/table-reservations/'):r.url().endsWith('/reservations')));await form.getByRole('button',{name:edit?'Save Reservation Changes':'Reserve This Table',exact:true}).click();const response=await wait;assert(response.ok(),await response.text());return response.json();};
 await page.goto(base+'/reservations?table='+a.id);await waitValue('Time','23:00');await waitValue('End Time','00:00');
 await page.waitForFunction(id=>document.querySelector('select[aria-label="Select Table"]')?.value===id,b.id);
 assert.equal(await field('Month').inputValue(),'12');assert.equal(await field('Day').inputValue(),'31');assert.equal(await field('End Month').inputValue(),'1');assert.equal(await field('End Day').inputValue(),'1');
 assert.equal(await form.locator('input[type="date"],input[type="datetime-local"],input[aria-label*="Year"]').count(),0);
 assert((await form.locator('[data-reservation-nearby]').innerText()).includes('Table 77'));
 check('server-timezone next-hour start and one-hour end cross the year without year inputs; nearby session selects its table');
 // A failed date resolver must never submit the previous automatic end for a newly typed start.
 await page.waitForFunction(()=>!document.querySelector('[data-reservation-form] button[type="submit"], [data-reservation-form] button:not([type])')?.disabled);
 let failedCandidate=false,reservationWrites=0;
 const countWrites=request=>{if(request.method()==='POST'&&request.url().endsWith('/reservations'))reservationWrites++;};page.on('request',countWrites);
 const candidateFailure=async route=>{const url=new URL(route.request().url());if(!failedCandidate&&url.searchParams.get('time')==='23:10'){failedCandidate=true;await route.fulfill({status:503,json:{detail:{code:'requestFailed'}}});}else await route.continue();};
 await page.route('**/reservation-candidates?*',candidateFailure);await field('Time').fill('23:10');
 const retry=form.getByRole('button',{name:'Retry Time Check',exact:true});await retry.waitFor();
 assert(failedCandidate);assert.equal(await field('Time').inputValue(),'23:10');assert.equal(await field('End Time').inputValue(),'00:00');
 assert(await form.getByRole('button',{name:'Reserve This Table',exact:true}).isDisabled());
 await form.evaluate(element=>element.requestSubmit());await form.getByRole('status').filter({hasText:'Retry before saving'}).waitFor();assert.equal(reservationWrites,0);
 await retry.click();await waitValue('End Time','00:10');
 await page.waitForFunction(()=>!document.querySelector('[data-reservation-form] button[type="submit"], [data-reservation-form] button:not([type])')?.disabled);
 assert.equal(await field('Time').inputValue(),'23:10');assert.equal(reservationWrites,0);await page.unroute('**/reservation-candidates?*',candidateFailure);page.off('request',countWrites);
 check('a failed start-time lookup preserves inputs and blocks all saving until retry restores the automatic one-hour end');
 await field('Time').fill('23:40');await waitValue('End Time','00:40');await field('End Time').fill('01:15');await field('Time').fill('23:50');
 await page.getByRole('button',{name:'CN',exact:true}).click();assert.equal(await form.getByLabel('结束时间',{exact:true}).inputValue(),'01:15');await page.getByRole('button',{name:'EN',exact:true}).click();
 await page.waitForResponse(response=>new URL(response.url()).pathname==='/api/club-tables'&&response.request().method()==='GET');assert.equal(await field('End Time').inputValue(),'01:15');
 await form.getByRole('button',{name:'Reset to One Hour',exact:true}).click();await waitValue('End Time','00:50');
 await field('End Month').fill('12');await field('End Day').fill('31');await field('End Time').fill('23:20');
 const rejectedResponse=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().endsWith('/reservations'));await form.getByRole('button',{name:'Reserve This Table',exact:true}).click();const rejected=await rejectedResponse;assert.equal(rejected.status(),409);await form.getByRole('status').filter({hasText:'The end must be after the start'}).waitFor();
 check('an end before the start is rejected without losing the typed reservation');
 await field('End Month').fill('1');await field('End Day').fill('1');await field('End Time').fill('02:30');const own=await save();assert.equal(own.session_id,first.session_id);assert.equal(own.start_at,'2027-01-01T07:50:00.000+00:00');assert.equal(own.end_at,'2027-01-01T10:30:00.000+00:00');
 check('end follows start until manually edited, survives language and background updates, and resets explicitly to one hour');
 const group=page.locator('[data-reservation-session="'+own.session_id+'"]');await group.locator('[data-reservation-id="'+own.id+'"]').waitFor();assert.equal(await page.locator('[data-reservation-session]').count(),1);
 assert((await group.innerText()).includes('23:20')&&(await group.innerText()).includes('02:30'));assert.equal(await group.locator('[data-reservation-id]').count(),2);
 assert.equal(await group.locator('[data-reservation-id="'+own.id+'"] [data-account-avatar]').count(),1);
 check('two independently owned reservations retain their times beneath one session range with participant avatars');
 await post(admin,'/api/table-reservations/'+first.id,{version:first.version,participant_ids:['photo-user-3','photo-user-2']});
 await tableSelect.selectOption(a.id);await field('Time').fill('23:35');await waitValue('End Time','00:35');await page.waitForTimeout(700);assert.equal(await tableSelect.inputValue(),a.id);
 const separate=await save();assert.equal(separate.table_id,a.id);assert.notEqual(separate.session_id,own.session_id);
 check('a manually selected table remains selected and is respected by the save request');
 await page.goto(base+'/reservations?table='+b.id);const ownRow=page.locator('[data-reservation-id="'+own.id+'"]');await ownRow.getByRole('button',{name:'Edit Reservation',exact:true}).click();
 await waitValue('Time','23:50');await waitValue('End Time','02:30');await field('Time').fill('23:55');await page.waitForTimeout(600);assert.equal(await field('End Time').inputValue(),'02:30');const edited=await save(true);assert.equal(edited.session_id,own.session_id);assert.equal(edited.end_at,own.end_at);
 check('editing retains the original start/end and changing the start preserves the existing custom end');
 await page.goto(base+'/?page=record&table='+encodeURIComponent(b.score_table_id));const frame=page.frameLocator('#record-game iframe');await frame.locator('#reservation-reminders').waitFor({state:'visible'});
 assert.equal(await frame.locator('[data-reservation-reminder]').count(),1);assert.equal(await frame.locator('[data-reservation-participant]').count(),2);
 assert((await frame.locator('#reservation-reminders').innerText()).includes('02:30'));assert(!(await frame.locator('#reservation-reminders').innerText()).includes('photo-user-'));
 await frame.locator('[data-seat-card="east"][data-seat-state="empty"]').waitFor();await frame.locator('[data-seat-card="east"]').click();await frame.locator('[data-reservation-participant][data-seat="east"]').waitFor();
 assert.equal(await frame.locator('[data-seat-card="east"] [data-account-avatar]').count(),1);
 check('Game Record shows one union of participants and the complete session range, with live seating and avatars');
 fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'fixture-session-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'fixture-session-mobile.png'),fullPage:true});
 // Past the old +/-one-hour rule but before the session ends: the reminder remains.
 fs.writeFileSync(process.env.SESSION_TEST_CLOCK,'2027-01-01T01:30:00-08:00');await page.waitForTimeout(2400);assert(await frame.locator('#reservation-reminders').isVisible());
 fs.writeFileSync(process.env.SESSION_TEST_CLOCK,'2027-01-01T02:31:00-08:00');await frame.locator('#reservation-reminders').waitFor({state:'hidden'});
 check('the session reminder remains until the latest end and disappears after the session ends');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'session-browser.json'),JSON.stringify({passed:true,checks,errors},null,2));console.log('Reservation sessions passed '+checks.length+' checks.');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
