/* Date-window competitions share the global session and language. */
const challengeT=(language,key)=>MahjongI18n.t(language,key);
async function challengeApi(path,body){
  const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...(body===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})});
  const value=await response.json();if(!response.ok)throw new Error(value.code||"competition_unavailable");return value;
}
function challengeDate(stamp,zone,language,time=false){return new Intl.DateTimeFormat(language==="CN"?"zh-CN":"en-US",{timeZone:zone,year:"numeric",month:"short",day:"numeric",...(time?{hour:"2-digit",minute:"2-digit",hourCycle:"h23"}:{})}).format(new Date(stamp));}
function challengeLocal(stamp,zone){const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(stamp)).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
function ChallengeMarkdown({text}){
  // Authored content is rendered only as text nodes: safe headings, lists and paragraphs.
  const nodes=[];let paragraph=[],items=[];
  const flushParagraph=()=>{if(paragraph.length){nodes.push(<p key={nodes.length} className="whitespace-pre-wrap">{paragraph.join("\n")}</p>);paragraph=[];}};
  const flushList=()=>{if(items.length){nodes.push(<ul key={nodes.length} className="list-disc space-y-1 pl-5">{items.map((v,i)=><li key={i}>{v}</li>)}</ul>);items=[];}};
  for(const line of String(text||"").split("\n")){
    if(/^#{1,3} /.test(line)){flushParagraph();flushList();nodes.push(<h3 key={nodes.length} className="text-lg font-bold">{line.replace(/^#{1,3} /,"")}</h3>);}
    else if(/^[-*] /.test(line)){flushParagraph();items.push(line.slice(2));}
    else if(!line.trim()){flushParagraph();flushList();}
    else{flushList();paragraph.push(line);}
  }
  flushParagraph();flushList();return <div className="space-y-3 leading-relaxed" data-challenge-prose>{nodes}</div>;
}
function ChallengeBoard({rows,competition,language,details,onDetails}){
  const t=k=>challengeT(language,k);
  return <div className="overflow-x-auto"><table className="w-full text-left text-sm" data-challenge-board><thead><tr className="border-b text-zinc-500">{["challengeRank","challengeName","challengeTotal","challengeGames"].map(k=><th key={k} className="px-2 py-3">{t(k)}</th>)}{[1,2,3,4].map(n=><th key={n} className="hidden px-2 py-3 lg:table-cell">{language==="CN"?`${n}位`:`${n}${n===1?"st":n===2?"nd":n===3?"rd":"th"}`}</th>)}{["challengePlacementSubtotal","challengeParticipationSubtotal"].map(k=><th key={k} className="hidden px-2 py-3 lg:table-cell">{t(k)}</th>)}</tr></thead><tbody>{rows.map(row=><React.Fragment key={row.key}><tr className="border-b border-zinc-100"><td className="px-2 py-4 font-bold">{row.rank}</td><td className="max-w-[130px] break-words px-2 py-4"><button type="button" className="text-left font-semibold underline decoration-zinc-300 underline-offset-4" aria-expanded={details?.key===row.key} onClick={()=>onDetails(row.key)}>{row.name}{row.type==="guest"&&<span className="ml-1 text-xs text-zinc-500">Guest</span>}</button></td><td className="px-2 py-4 text-lg font-black text-navy">{row.total}</td><td className="px-2 py-4">{row.games}</td>{row.placements.map((n,i)=><td key={i} className="hidden px-2 lg:table-cell">{n}</td>)}<td className="hidden px-2 lg:table-cell">{row.placement_score}</td><td className="hidden px-2 lg:table-cell">{row.participation_score}</td></tr>{details?.key===row.key&&<tr><td colSpan="10" className="bg-warm p-4"><p className="mb-3 font-semibold">{t("challengeDetails")} · {row.name}</p><p className="mb-3 text-xs">1 / 2 / 3 / 4: {row.placements.join(" / ")} · {t("challengePlacementSubtotal")}: {row.placement_score} · {t("challengeParticipationSubtotal")}: {row.participation_score}</p>{details.loading?<p>…</p>:details.error?<p role="alert">{t(details.error)}</p>:<ul className="space-y-2">{details.rows.map((game,i)=><li key={i} className="flex flex-wrap gap-x-4 gap-y-1 text-xs"><span>{challengeDate(game.played_at,competition.timezone,language,true)}</span><span>#{game.placement}</span><span>{game.placement_score} + {game.participation_score} = <b>{game.total_score}</b></span></li>)}</ul>}</td></tr>}</React.Fragment>)}</tbody></table></div>;
}
function CurrentChallenge({language,full=false}){
  const [data,setData]=React.useState(null),[error,setError]=React.useState(""),[query,setQuery]=React.useState(""),[details,setDetails]=React.useState(null);
  const slug=full?decodeURIComponent(location.pathname.split("/")[2]||""):"featured";const t=k=>challengeT(language,k);
  async function refresh(){try{setData(await challengeApi("/api/competitions/"+encodeURIComponent(slug)+"?q="+encodeURIComponent(query)));setError("");}catch(e){setError(e.message);}}
  React.useEffect(()=>{let active=true;const load=async()=>{try{const next=await challengeApi("/api/competitions/"+encodeURIComponent(slug)+"?q="+encodeURIComponent(query));if(active){setData(next);setError("");}}catch(e){if(active)setError(e.message);}};load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[slug,query]);
  async function toggle(key){if(details?.key===key){setDetails(null);return;}setDetails({key,loading:true});try{const body=await challengeApi("/api/competitions/"+data.competition.slug+"?participant="+encodeURIComponent(key));setDetails({key,rows:body.details});}catch(e){setDetails({key,error:e.message});}}
  if(!data?.competition&&!error)return null;
  if(!data?.competition)return <Card><p role="alert">{t(error)}</p><button onClick={refresh}>{t("challengeRetry")}</button></Card>;
  const c=data.competition,ph=t("challenge"+c.phase[0].toUpperCase()+c.phase.slice(1));
  return <section className="mb-6" data-i18n-owned data-current-challenge><Card>
    <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-widest text-zinc-500">{t("challengeHeading")}</p><span className={`rounded-full px-3 py-1 text-xs font-bold ${c.phase==="live"?"bg-green-100 text-green-800":"bg-amber-50 text-amber-900"}`}>{ph}</span></div>
    <h2 className="text-2xl font-black text-navy sm:text-3xl">{c.title}</h2><p className="mt-2 text-sm text-zinc-600">{challengeDate(c.start_at,c.timezone,language)} – {challengeDate(new Date(Date.parse(c.end_at)-1),c.timezone,language)} · {c.timezone}</p>
    {c.cover&&<img className="mt-5 max-h-80 w-full rounded-xl object-contain bg-warm" src={c.cover.src} srcSet={`${c.cover.src} 640w, ${c.cover.large} 1280w`} sizes="(max-width: 640px) 100vw, 1000px" alt={c.cover.alt} loading="lazy"/>}
    <div className="mt-5"><ChallengeMarkdown text={c.introduction}/></div>
    {c.images.length>0&&<div className="my-5 grid gap-4 sm:grid-cols-2">{c.images.map(i=><img key={i.key} src={i.src} srcSet={`${i.src} 640w, ${i.large} 1280w`} sizes="(max-width: 640px) 100vw, 500px" className="w-full rounded-xl" loading="lazy" alt={i.alt}/>)}</div>}
    <div className="my-5 rounded-xl border border-amber-100 bg-amber-50 p-4"><h3 className="mb-2 font-bold">{t("challengeRules")}</h3><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-4">{c.rules.placements.map((n,i)=><p key={i}>{language==="CN"?`第 ${i+1} 名`:`${i+1}${["st","nd","rd","th"][i]}`}: <b>{n}</b></p>)}</div><p className="mt-2 text-sm">{t("challengeParticipation")}: <b>{c.rules.participation}</b></p><p className="mt-2 text-xs">{t("challengeAutomatic")}</p></div>
    {full&&<label className="mb-4 block text-sm">{t("challengeSearch")}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label>}
    {error&&<p role="alert" className="text-red-700">{t(error)}</p>}
    {!c.leaderboard_public?<p>{t("challengePrivate")}</p>:!data.leaderboard.length?<p className="rounded-xl bg-warm p-5 text-sm text-zinc-600">{t("challengeNoGames")}</p>:<ChallengeBoard rows={data.leaderboard} competition={c} language={language} details={details} onDetails={toggle}/>}
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-zinc-500">{t("challengeUpdated")}: {challengeDate(c.updated_at,c.timezone,language,true)}</p><a className="rounded-xl bg-navy px-4 py-3 text-sm font-bold text-white" href={full?"/":"/challenges/"+encodeURIComponent(c.slug)}>{t(full?"challengeBack":"challengeFull")}</a></div>
  </Card></section>;
}
function ChallengeAdmin({language,profile}){
  const t=k=>challengeT(language,k),[choices,setChoices]=React.useState([]),[slug,setSlug]=React.useState(""),[body,setBody]=React.useState(null),[form,setForm]=React.useState(null),[rules,setRules]=React.useState(null),[busy,setBusy]=React.useState(false),[message,setMessage]=React.useState(""),[alt,setAlt]=React.useState(""),[records,setRecords]=React.useState(null),[reason,setReason]=React.useState(""),[checked,setChecked]=React.useState(false),[unlock,setUnlock]=React.useState(false);
  const field="mt-1 w-full rounded-xl border border-zinc-300 p-3 text-sm";
  React.useEffect(()=>{if(profile?.is_admin)challengeApi("/api/competitions/manage").then(r=>{setChoices(r.competitions);setSlug(old=>old||r.competitions[0]?.slug||"");}).catch(e=>setMessage(e.message));},[profile?.id]);
  async function load(preserve=false){if(!slug)return;const next=await challengeApi("/api/competitions/"+slug+"/admin");setBody(next);const c=next.competition;setForm(old=>preserve&&old?old:{...c.draft,published:c.published,featured:c.featured,leaderboard_public:c.leaderboard_public});setRules({start_at:challengeLocal(c.start_at,c.timezone),end_at:challengeLocal(c.end_at,c.timezone),placements:c.rules.placements,participation:c.rules.participation});}
  React.useEffect(()=>{load().catch(e=>setMessage(e.message));setRecords(null);},[slug]);
  if(!profile?.is_admin)return null;
  async function act(action,data){setBusy(true);setMessage("");try{await challengeApi("/api/competitions/"+slug+"/"+action,data);await load(action==="images"||action==="image-delete");setMessage("challengeSaved");}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  async function saveRules(rebuild_now){if(!checked||!window.confirm(t("challengeConfirm")))return;await act("rules",{version:body.competition.version,confirmation:slug,reason,rebuild_now,unlock_ended:unlock,start_at:rules.start_at,end_at:rules.end_at,rules:{placements:rules.placements.map(Number),participation:Number(rules.participation)}});setChecked(false);}
  async function upload(file){if(!file)return;if(file.size>2*1024*1024){setMessage("image_too_large");return;}const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});await act("images",{data,alt});}
  function move(index,delta){const next=[...form.images],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setForm({...form,images:next});}
  return <div data-i18n-owned className="mb-6"><Card><h2 className="mb-4 text-xl font-bold">{t("challengeManage")}</h2><select aria-label={t("challengeManage")} className={field} value={slug} onChange={e=>setSlug(e.target.value)}>{choices.map(c=><option key={c.slug} value={c.slug}>{c.title}</option>)}</select>{message&&<p role="status" className="my-3 rounded-xl bg-warm p-3 text-sm">{t(message)}</p>}
    {body&&form&&rules&&<fieldset disabled={busy} className="mt-5 space-y-5"><label className="block text-sm font-bold">{t("challengeTitle")}<input aria-label={t("challengeTitle")} className={field} maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="block text-sm font-bold">{t("challengeIntro")}<textarea aria-label={t("challengeIntro")} className={field} rows={8} maxLength={20000} value={form.introduction} onChange={e=>setForm({...form,introduction:e.target.value})}/></label>
      <div className="rounded-xl bg-warm p-4"><ChallengeMarkdown text={form.introduction}/></div><div className="flex flex-wrap gap-4">{["published","featured","leaderboard_public"].map((k,i)=><label key={k} className="text-sm"><input type="checkbox" checked={form[k]} onChange={e=>setForm({...form,[k]:e.target.checked})}/> {t(["challengePublished","challengeFeatured","challengePublic"][i])}</label>)}</div>
      <label className="block text-sm">{t("challengeAlt")}<input aria-label={t("challengeAlt")} className={field} value={alt} onChange={e=>setAlt(e.target.value)} maxLength={300}/></label><label className="block text-sm">{t("challengeUpload")}<input className="mt-2 block w-full" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{upload(e.target.files[0]).catch(()=>setMessage("competition_unavailable"));e.target.value="";}}/></label>
      <label className="block text-sm">{t("challengeCover")}<select aria-label={t("challengeCover")} className={field} value={form.cover||""} onChange={e=>setForm({...form,cover:e.target.value||null})}><option value="">{t("challengeNone")}</option>{body.competition.available_images.map((i,n)=><option key={i.key} value={i.key}>{i.alt||`${t("challengeCover")} ${n+1}`}</option>)}</select></label>
      <div><p className="mb-2 text-sm font-bold">{t("challengeImages")}</p>{form.images.map((key,n)=>{const img=body.competition.available_images.find(i=>i.key===key);return <div key={n} className="mb-2 flex flex-wrap items-center gap-2 rounded-xl border p-2">{img&&<img src={img.src} alt={img.alt} className="h-12 w-16 object-cover"/>}<span className="text-xs">{img?.alt}</span><button type="button" onClick={()=>move(n,-1)}>{t("challengeEarlier")}</button><button type="button" onClick={()=>move(n,1)}>{t("challengeLater")}</button><button type="button" onClick={()=>setForm({...form,images:form.images.filter((_,i)=>i!==n)})}>{t("challengeRemove")}</button></div>;})}<select aria-label={t("challengeAddImage")} className={field} value="" onChange={e=>{if(e.target.value)setForm({...form,images:[...form.images,e.target.value]});}}><option value="">{t("challengeAddImage")}</option>{body.competition.available_images.filter(i=>!form.images.includes(i.key)).map((i,n)=><option key={i.key} value={i.key}>{i.alt||`${n+1}`}</option>)}</select></div>
      <div className="flex flex-wrap gap-2">{body.competition.available_images.filter(i=>i.key!==form.cover&&!form.images.includes(i.key)).map((i,n)=><button key={i.key} type="button" className="rounded-lg border px-3 py-2 text-xs" onClick={()=>act("image-delete",{key:i.key})}>{t("challengeDeleteImage")}: {i.alt||n+1}</button>)}</div>
      <div className="flex flex-wrap gap-3"><button type="button" className="rounded-xl border px-4 py-3 text-sm font-bold" onClick={()=>act("content",{...form,version:body.competition.version,publish:false})}>{t("challengeDraft")}</button><button type="button" className="rounded-xl bg-navy px-4 py-3 text-sm font-bold text-white" onClick={()=>act("content",{...form,version:body.competition.version,publish:true})}>{t("challengePublish")}</button></div>
      <details className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">{t("challengeSettings")}</summary><p className="my-3 text-sm text-amber-800">{t("challengeRuleWarning")}</p><p className="text-xs">{body.competition.timezone} · {t("challengeAutomatic")}</p>{body.competition.pending_rules&&<p role="status" className="text-amber-800">{t("challengePending")}</p>}<div className="my-3 grid gap-3 sm:grid-cols-2">{["start_at","end_at"].map((k,i)=><label key={k} className="text-sm">{t(i?"challengeEnd":"challengeStart")}<input className={field} type="datetime-local" value={rules[k]} onChange={e=>setRules({...rules,[k]:e.target.value})}/></label>)}</div><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{rules.placements.map((value,n)=><label key={n} className="text-sm">{n+1}<input aria-label={`Placement ${n+1}`} className={field} type="number" step="0.0001" value={value} onChange={e=>setRules({...rules,placements:rules.placements.map((v,i)=>i===n?e.target.value:v)})}/></label>)}<label className="text-sm">{t("challengeParticipation")}<input className={field} type="number" step="0.0001" value={rules.participation} onChange={e=>setRules({...rules,participation:e.target.value})}/></label></div><label className="my-3 block text-sm">{t("challengeReason")}<input className={field} value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label><label className="my-3 block text-sm"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> {t("challengeConfirmRules")}</label>{profile.is_super_admin&&<label className="mb-3 block text-sm"><input type="checkbox" checked={unlock} onChange={e=>setUnlock(e.target.checked)}/> {t("challengeUnlock")}</label>}<div className="flex flex-wrap gap-3">{[true,false].map(now=><button type="button" disabled={!checked||!reason} key={String(now)} className="rounded-xl border px-3 py-2 text-sm disabled:opacity-40" onClick={()=>saveRules(now)}>{t(now?"challengeRebuildNow":"challengeDefer")}</button>)}<button type="button" disabled={!reason} className="rounded-xl border px-3 py-2 text-sm disabled:opacity-40" onClick={()=>{if(window.confirm(t("challengeConfirm")))act("rebuild",{reason,confirmation:slug,unlock_ended:unlock});}}>{t("challengeRebuild")}</button></div></details>
      <details className="rounded-xl border p-4"><summary className="cursor-pointer font-bold">{t("challengeEligible")} ({body.competition.eligible_users.length}) · {t("challengeActive")} ({body.participant_count})</summary><div className="mt-3 flex flex-wrap gap-3 text-sm">{body.competition.eligible_users.map((p,n)=><span key={n}>{p.name}{p.type==="guest"?" · Guest":""}</span>)}</div></details>
      <details className="rounded-xl border p-4" onToggle={e=>{if(e.target.open)challengeApi("/api/competitions/"+slug+"/games").then(r=>setRecords(r.games)).catch(e=>setMessage(e.message));}}><summary className="cursor-pointer font-bold">{t("challengeRecords")}</summary>{records?.map(game=><ChallengeGameEditor key={game.game_key} game={game} language={language} timezone={body.competition.timezone} save={async data=>{await act("game-correction",data);const next=await challengeApi("/api/competitions/"+slug+"/games");setRecords(next.games);}}/>)}</details>
    </fieldset>}
  </Card></div>;
}
function ChallengeGameEditor({game,language,timezone,save}){
  const t=k=>challengeT(language,k),[state,setState]=React.useState(game.status),[positions,setPositions]=React.useState(Object.fromEntries(game.players.map(p=>[p.identity_key,p.placement]))),[reason,setReason]=React.useState("");
  return <div className="mt-3 rounded-xl bg-warm p-4"><p className="text-sm font-bold">{challengeDate(game.played_at,timezone,language,true)} · {game.source}</p><div className="my-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{game.players.map(p=><label key={p.identity_key} className="text-xs">{p.name}<select className="mt-1 w-full rounded-lg border p-2" value={positions[p.identity_key]} onChange={e=>setPositions({...positions,[p.identity_key]:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label>)}</div><label className="text-sm">{t("challengeStatus")}<select className="m-2 rounded-lg border p-2" value={state} onChange={e=>setState(e.target.value)}>{["confirmed","void","cancelled","test","duplicate"].map((k,i)=><option key={k} value={k}>{t(["challengeConfirmed","challengeVoid","challengeCancelled","challengeTest","challengeDuplicate"][i])}</option>)}</select></label><input aria-label={t("challengeReason")} placeholder={t("challengeReason")} className="mb-2 w-full rounded-lg border p-2 text-sm" value={reason} onChange={e=>setReason(e.target.value)}/><button type="button" disabled={!reason} className="rounded-xl border bg-white px-3 py-2 text-sm disabled:opacity-40" onClick={()=>save({game_key:game.game_key,status:state,placements:positions,reason})}>{t("challengeCorrect")}</button></div>;
}
